[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rtd"
version = "0.1.0"
description = "Real-time diffusion tools"
authors = [
  { name = "Your Name", email = "info@lunar-ring.ai" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
  "huggingface_hub<1.0",
  "diffusers",
  "torch",
  "Pillow",
  "numpy"
]

[tool.setuptools.packages.find]
where = ["src"]
